### ISSUE TITLE
Can you help?

### ISSUE THREAD

**Issue by t0mtee** [CosmoCortney/PPC-Cheat-Code-Handler#1]
This may sound super nooby, but can you show me how to install this. Like, a step by step guide from the beginning? Thanks. 😀

**Comment by t0mtee** [comment]
Or just send me the .elf file? Either way.

**Comment by CosmoCortney** [comment]
Check out the cheat code thread over on GBAtemp.
But the recent release of TCPGecko.elf already has the codehandler included

**Comment by t0mtee** [comment]
ahhh ok thx
